### ISSUE TITLE
Viewer on site does not load 

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/lymemind-commons-schema#3]
https://commons.lymemind.org/#/Viewer

**Comment by u8sand** [comment]
This viewer is a completely standalone static site. somehow it is no longer present in the container (?) We could also run this site on github.io potentially.

Attached is the site
[webview.tar.gz](https://github.com/MaayanLab/lymemind-commons-schema/files/9566566/webview.tar.gz)

Code is here: https://github.com/LymeMIND/LM2-study-supporting-materials/tree/main/webview

I've deployed it with github-io in the LM2-study-support-material repo, which serves the viewer at: https://lymemind.github.io/LM2-study-supporting-materials/

**Comment by AviMaayan** [comment]
@jeevangelista can you update the URL in the iframe in LymeMIND Commons?

**Comment by jeevangelista** [comment]
updated
